### PR TITLE
Added meson build system and updated README

### PR DESCRIPTION
**Pull request by joanimato**
Added the ability to compile with meson (https://mesonbuild.com/) and added a new README.md with updated installation instructions.

### CODE REVIEW

**Comment by atillack** [comment]
@joanimato Nice work! I like it. Let's merge the two README files please: the general description could be added to the new one and the original compile instructions could get their own section further below.

**Comment by joanimato** [comment]
@atillack Could do, but I think autoconf requires a README file (without the .md) whereas github can only parse README.md correctly. I guess we could just keep the README without the markdown formatting.

**Comment by atillack** [comment]
Newer autotool versions support .md but we could also simply have only README (Github can live w/o the .md when starting the file with `<!-- vim: syntax=Markdown -->`) but with markup. Better than building up a legacy Readme file - if it's worth doing a new Readme file (which I think it is) then let's do that.

**Comment by atillack** [comment]
Alternatively we could work around older autotool limitations following:
https://stackoverflow.com/questions/15013672/use-autotools-with-readme-md

**Review by atillack — APPROVED** [review]
Thank you. Approved 😀

**Comment by diogomart** [comment]
Thanks @joanimato the mason build works on my workstation

**Pull request merged**
